### ISSUE TITLE
2022-08-04 Email generation edge case bugs

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/DECIDE-WP3-newsletter#53]
4 emails failed to generate. 4/800 = 0.5% which is a pretty low error rate all things considered

73
```
Quitting from lines 556-747 (v0_0_7.Rmd) 
Error: Argument 'txt' must be a JSON string, URL or file.
```

- [ ] This is something to do with the response from the DECIDE tool API when getting suggestions for 'going the extra mile', possibly trying a location outside of the DECIDE map.

108
```
https://nominatim.openstreetmap.org/reverse?lat=49.219&lon=-2.22299999999999&format=json not reachable.
Quitting from lines 556-747 (v0_0_7.Rmd) 
Error: Argument 'txt' must be a JSON string, URL or file.
```
- [ ] Nominatim failure

559, 566
```
Quitting from lines 121-168 (v0_0_7.Rmd) 
Error in .pointsToMatrix(y) : longitude < -360
```

- [x] Something to do with geosphere package. Need to remove rows where longitude is below 360?

**Comment by simonrolph** [comment]
Issues for 73 and 108 are due to the people being from jersey

**Comment by AugustT** [comment]
Nice work. the -360 is odd. I wonder if a 0 somewhere was producing a -Inf. Just guessing wildly!
