### ISSUE TITLE
Some jobs failed on JASMIN due to fatal error

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/DECIDE-WP3-newsletter#60]
About 100 jobs failed when rendering MyDECIDE on JASMIN. Error log files give this error:

```
Fatal error: cannot create 'R_TempDir'
```

Probably nothing I can do about this other than rerun the script.

**Comment by AugustT** [comment]
I wonder if you have run out of storage space whereever it is trying to creat the temp folder?
